### ISSUE TITLE
Chapter 15 issues

### ISSUE THREAD

**Issue by daichen-daisy** [edgedb/easy-edgedb#40]
### Issues:
1. line 31: I think you should want to write `Around 1 or 2 am`, it's "am", not "pm".
2. line 84: I think the operator is `??`, not single `?`.
3. line 327: Q4 in "Time to practice". Maybe you want to use `NPC`, not `PC`, right? Because you used `NPC` type in the answer. (answer is [here](https://github.com/edgedb/easy-edgedb/blob/master/chapter15/answers.md))

### Questions:
1. line 82: sorry about that, I am a little bit confused about `you can change the return type to `-> OPTIONAL str`, maybe because I am a newbie. The current text is suggesting that, in order to have this function called all the time regardless of the given parameter value, the return type should be optional. But I think we should actually make the *parameter* type optional, right? The optional return type is just to tell the user this function may return an empty set.
2. line 258: why is this the best way to start with a property called `master_name` that is just a string? Actually, after I tried those example codes in my local, I found we could get the same result absolutely without the `master_name`. So why do we have to keep with it all the time?

**Comment by Dhghomon** [comment]
Issues 1, 2, 3: all yes. Thank you!

line 82: this was changed after the discussion for the same chapter: https://github.com/edgedb/easy-edgedb/issues/26

>This is slightly incorrect signature, the return type should be OPTIONAL str, because technically the vampire may end up an {}.

Yes, doing the same on the parameter I think would work but here we're just focusing on giving the user some experience with how to make and use functions (maybe the user has been given a schema that higher-ups don't want altered for example).

LIne 258: we're not actually keeping the `master_name`, just practicing reverse links:

>(Note: we won't actually change the `MinorVampire` type here because we already know how to access `Vampire` with a reverse lookup, but this is how to do it)

The background to this is that reverse links took me the longest to figure out in EdgeDB because there were only two examples of them in the whole documentation at the time (that I could find, at least). Then when I finally figured them out they became really useful and I decided I would fill the book with examples of using it so that later readers would be overexposed to it. There might be *too* many examples of it (like here where we're just doing it for fun and not even changing the schema) but I wanted to err on the side of having too much information rather than too little. IMO it's better to have the user roll their eyes at yet another example of reverse links ("oh God, I already *know* reverse links") than finish the book without being comfortable with how to use them.

Looks like you've already translated up to Chapter 15? That's quite a bit!

**Comment by vpetrovykh** [comment]
Regarding the `Vampire` and `MinorVampire` relationship. The paragraph preceding this change doesn't need to create `master_name` first, the whole point is that `master` link can be derived directly by following the already existing link `slaves` in reverse.

This brings us to the more subtle point of what's the preferred way of setting up links. Consider these two snippets:
```
type Vampire extending Person { 
    multi link slaves -> MinorVampire;
}

type MinorVampire extending Person {
    link former_self -> Person;
    link master := (SELECT .<slaves[IS Vampire] LIMIT 1);
}
```
vs
```
type Vampire extending Person { 
    multi link slaves := .<master[IS MinorVampire];
}

type MinorVampire extending Person {
    link former_self -> Person;
    required link master -> Vampire;
}
```

These two produce equivalent relationships `master` and `slaves` between `Vampire` and `MinorVampire` and make no real difference in querying. However, inserting and updating changes depending on which schema you choose (and there could be reasons to prefer one form over the other). All other things being equal the second snippet is more idiomatic (rule of thumb is that single links are easier to work with and reason about than multi links and thus are preferred).

**Comment by daichen-daisy** [comment]
line 82: @Dhghomon 
> Yes, doing the same on the parameter I think would work 

I have given it a try today, and the function won't be called if the parameter is an empty set when I only put `OPTIONAL` on the return type but not the parameter type.


line 258: @Dhghomon about `master_name`, I think removing it as @vpetrovykh said [here](https://github.com/edgedb/easy-edgedb/issues/26#issuecomment-867775997) would be more clear to me as a reader.


> Looks like you've already translated up to Chapter 15? That's quite a bit!

Yes, maybe I could finish the translation next week and start the first round revision.
